title = "gitleaks config"

[allowlist]
paths = [
    '''gitleaks\.toml''',
    '''(?i)\.(bmp|gif|jpe?g|svg|tiff?)$''',
    '''(.*?)(doc|docx|zip|xls|pdf|bin)$''',
    '''go\.(mod|sum)$'''
]

[[rules]]
id = "aws-access-key"
description = "AWS Access Key"
regex = '''(A3T[A-Z0-9]|AKIA|AGPA|AIDA|AROA|AIPA|ANPA|ANVA|ASIA)[A-Z0-9]{16}'''

[[rules]]
id = "github-pat"
description = "Github Personal Access Token"
regex = '''ghp_[0-9a-zA-Z]{36}'''
