# Gitleaks configuration v8
[allowlist]
  paths = [
    'gitleaks\.toml',
    '(?i).*\.(png|jpg|gif|doc|docx|pdf|bin|xls|pyc|zip)$',
    'go\.(mod|sum)$'
  ]

[[rules]]
  id = 'aws-access-key'
  description = 'AWS Access Key'
  regex = '(A3T[A-Z0-9]|AKIA|AGPA|AIDA|AROA|AIPA|ANPA|ANVA|ASIA)[A-Z0-9]{16}'
  tags = ['key', 'AWS']

[[rules]]
  id = 'aws-secret-key'
  description = 'AWS Secret Key'
  regex = '''(?i)aws_(.{0,20})?=?.['"0-9a-zA-Z\/+]{40}'''
  tags = ['key', 'AWS']

[[rules]]
  id = 'github-pat'
  description = 'Github Personal Access Token'
  regex = 'ghp_[0-9a-zA-Z]{36}'
  tags = ['key', 'Github']

[[rules]]
  id = 'github-oauth'
  description = 'Github OAuth Access Token'
  regex = 'gho_[0-9a-zA-Z]{36}'
  tags = ['key', 'Github']

[[rules]]
  id = 'github-app-token'
  description = 'Github App Token'
  regex = '(ghu|ghs)_[0-9a-zA-Z]{36}'
  tags = ['key', 'Github']

[[rules]]
  id = 'github-refresh-token'
  description = 'Github Refresh Token'
  regex = 'ghr_[0-9a-zA-Z]{76}'
  tags = ['key', 'Github']

[[rules]]
  id = 'slack-token'
  description = 'Slack Token'
  regex = 'xox[baprs]-([0-9a-zA-Z]{10,48})?'
  tags = ['key', 'Slack']

[[rules]]
  id = 'asymmetric-private-key'
  description = 'Asymmetric Private Key'
  regex = '-----BEGIN ((EC|PGP|DSA|RSA|OPENSSH) )?PRIVATE KEY( BLOCK)?-----'
  tags = ['key', 'AsymmetricPrivateKey']

[[rules]]
  id = 'google-api-key'
  description = 'Google API key'
  regex = 'AIza[0-9A-Za-z\-_]{35}'
  tags = ['key', 'Google']

[[rules]]
  id = 'google-service-account'
  description = 'Google (GCP) Service Account'
  regex = '"type": "service_account"'
  tags = ['key', 'Google']

[[rules]]
  id = 'heroku-api-key'
  description = 'Heroku API key'
  regex = '(?i)heroku(.{0,20})?[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}'
  tags = ['key', 'Heroku']

[[rules]]
  id = 'mailchimp-api-key'
  description = 'MailChimp API key'
  regex = '(?i)(mailchimp|mc)(.{0,20})?[0-9a-f]{32}-us[0-9]{1,2}'
  tags = ['key', 'Mailchimp']

[[rules]]
  id = 'mailgun-api-key'
  description = 'Mailgun API key'
  regex = '((?i)(mailgun|mg)(.{0,20})?)?key-[0-9a-z]{32}'
  tags = ['key', 'Mailgun']

[[rules]]
  id = 'paypal-braintree-token'
  description = 'PayPal Braintree access token'
  regex = 'access_token\$production\$[0-9a-z]{16}\$[0-9a-f]{32}'
  tags = ['key', 'Paypal']

[[rules]]
  id = 'picatic-api-key'
  description = 'Picatic API key'
  regex = 'sk_live_[0-9a-z]{32}'
  tags = ['key', 'Picatic']

[[rules]]
  id = 'sendgrid-api-key'
  description = 'SendGrid API Key'
  regex = 'SG\.[\w_]{16,32}\.[\w_]{16,64}'
  tags = ['key', 'SendGrid']

[[rules]]
  id = 'slack-webhook'
  description = 'Slack Webhook'
  regex = 'https://hooks.slack.com/services/T[a-zA-Z0-9_]{8}/B[a-zA-Z0-9_]{8,12}/[a-zA-Z0-9_]{24}'
  tags = ['key', 'slack']

[[rules]]
  id = 'stripe-api-key'
  description = 'Stripe API key'
  regex = '(?i)stripe(.{0,20})?[sr]k_live_[0-9a-zA-Z]{24}'
  tags = ['key', 'Stripe']

[[rules]]
  id = 'square-access-token'
  description = 'Square access token'
  regex = 'sq0atp-[0-9A-Za-z\-_]{22}'
  tags = ['key', 'square']

[[rules]]
  id = 'square-oauth-secret'
  description = 'Square OAuth secret'
  regex = 'sq0csp-[0-9A-Za-z\-_]{43}'
  tags = ['key', 'square']

[[rules]]
  id = 'twilio-api-key'
  description = 'Twilio API key'
  regex = '(?i)twilio(.{0,20})?SK[0-9a-f]{32}'
  tags = ['key', 'twilio']

[[rules]]
  id = 'dynatrace-token'
  description = 'Dynatrace token'
  regex = 'dt0[a-zA-Z]{1}[0-9]{2}\.[A-Z0-9]{24}\.[A-Z0-9]{64}'
  tags = ['key', 'Dynatrace']

[[rules]]
  id = 'shopify-shared-secret'
  description = 'Shopify shared secret'
  regex = 'shpss_[a-fA-F0-9]{32}'
  tags = ['key', 'Shopify']

[[rules]]
  id = 'shopify-access-token'
  description = 'Shopify access token'
  regex = 'shpat_[a-fA-F0-9]{32}'
  tags = ['key', 'Shopify']

[[rules]]
  id = 'shopify-custom-app-token'
  description = 'Shopify custom app access token'
  regex = 'shpca_[a-fA-F0-9]{32}'
  tags = ['key', 'Shopify']

[[rules]]
  id = 'shopify-private-app-token'
  description = 'Shopify private app access token'
  regex = 'shppa_[a-fA-F0-9]{32}'
  tags = ['key', 'Shopify']

[[rules]]
  id = 'pypi-upload-token'
  description = 'PyPI upload token'
  regex = 'pypi-AgEIcHlwaS5vcmc[A-Za-z0-9-_]{50,1000}'
  tags = ['key', 'pypi']
