title = "gitleaks config"

[allowlist]
paths = [
    "\\.gitleaks\\.toml$",
    "(.*?)(png|jpg|gif|doc|docx|pdf|bin|xls|pyc|zip)$",
    "(go\\.mod|go\\.sum)$"
]

[[rules]]
id = "aws-access-key"
description = "AWS Access Key"
regex = '(A3T[A-Z0-9]|AKIA|AGPA|AIDA|AROA|AIPA|ANPA|ANVA|ASIA)[A-Z0-9]{16}'
tags = ["key", "AWS"]

[[rules]]
id = "aws-secret-key"
description = "AWS Secret Key"
regex = '(?i)aws_(.{0,20})?=?.["0-9a-zA-Z\/+]{40}'
tags = ["key", "AWS"]

[[rules]]
id = "facebook-secret-key"
description = "Facebook Secret Key"
regex = "(?i)(facebook|fb)(.{0,20})?(?-i)['\"][0-9a-f]{32}['\"]"
tags = ["key", "Facebook"]

[[rules]]
id = "facebook-client-id"
description = "Facebook Client ID"
regex = "(?i)(facebook|fb)(.{0,20})?['\"][0-9]{13,17}['\"]"
tags = ["key", "Facebook"]

[[rules]]
id = "twitter-secret-key"
description = "Twitter Secret Key"
regex = "(?i)twitter(.{0,20})?['\"][0-9a-z]{35,44}['\"]"
tags = ["key", "Twitter"]

[[rules]]
id = "twitter-client-id"
description = "Twitter Client ID"
regex = "(?i)twitter(.{0,20})?['\"][0-9a-z]{18,25}['\"]"
tags = ["client", "Twitter"]

[[rules]]
id = "github-pat"
description = "Github Personal Access Token"
regex = 'ghp_[0-9a-zA-Z]{36}'
tags = ["key", "Github"]

[[rules]]
id = "asymmetric-private-key"
description = "Asymmetric Private Key"
regex = '-----BEGIN ((EC|PGP|DSA|RSA|OPENSSH) )?PRIVATE KEY( BLOCK)?-----'
tags = ["key", "AsymmetricPrivateKey"]

[[rules]]
id = "google-api-key"
description = "Google API key"
regex = 'AIza[0-9A-Za-z\-_]{35}'
tags = ["key", "Google"]

[[rules]]
id = "slack-token"
description = "Slack"
regex = 'xox[baprs]-([0-9a-zA-Z]{10,48})?'
tags = ["key", "Slack"]
